CREATE TABLE hospital
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    address      VARCHAR(255),
    phone_number VARCHAR(50),
    email        VARCHAR(255)
);

CREATE TABLE department
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    hospital_id BIGINT       NOT NULL,
    CONSTRAINT fk_department_hospital
        FOREIGN KEY (hospital_id)
            REFERENCES hospital (id)
            ON DELETE CASCADE
);

CREATE TABLE staff
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    oib          VARCHAR(11)  NOT NULL UNIQUE,
    birth_date   DATE         NOT NULL,
    role         VARCHAR(50)  NOT NULL,
    permissions  VARCHAR(50),
    email        VARCHAR(255) NOT NULL UNIQUE,
    salary       DOUBLE PRECISION,
    phone_number VARCHAR(50),
    address      VARCHAR(255),
    hospital_id  BIGINT,
    CONSTRAINT fk_staff_hospital
        FOREIGN KEY (hospital_id)
            REFERENCES hospital (id)
            ON DELETE SET NULL
);



CREATE TABLE ward
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    max_capacity  INT          NOT NULL,
    capacity      INT          NOT NULL,
    department_id BIGINT       NOT NULL,
    nurse_id      BIGINT,
    CONSTRAINT fk_ward_department
        FOREIGN KEY (department_id)
            REFERENCES department (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_ward_nurse
        FOREIGN KEY (nurse_id)
            REFERENCES staff (id)
            ON DELETE SET NULL
);
CREATE TABLE patient
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name         VARCHAR(100) NOT NULL,
    last_name          VARCHAR(100) NOT NULL,
    oib                VARCHAR(11)  NOT NULL UNIQUE,
    birth_date         DATE         NOT NULL,
    status             VARCHAR(50)  NOT NULL,
    mbo                VARCHAR(50)  NOT NULL UNIQUE,
    hospital_id        BIGINT,
    assigned_doctor_id BIGINT,
    ward_id            BIGINT,
    CONSTRAINT fk_patient_ward
        FOREIGN KEY (ward_id)
            REFERENCES ward (id)
            ON DELETE SET NULL,
    CONSTRAINT fk_patient_hospital
        FOREIGN KEY (hospital_id)
            REFERENCES hospital (id)
            ON DELETE SET NULL,
    CONSTRAINT fk_patient_doctor
        FOREIGN KEY (assigned_doctor_id)
            REFERENCES staff (id)
            ON DELETE SET NULL
);

CREATE TABLE appointment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id  BIGINT    NOT NULL,
    patient_id BIGINT    NOT NULL,
    date_time  TIMESTAMP NOT NULL,
    CONSTRAINT fk_appointment_doctor
        FOREIGN KEY (doctor_id)
            REFERENCES staff (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_appointment_patient
        FOREIGN KEY (patient_id)
            REFERENCES patient (id)
            ON DELETE CASCADE
);

CREATE TABLE prescription
(
    id          VARCHAR(255) PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    doctor_id   BIGINT       NOT NULL,
    patient_id  BIGINT       NOT NULL,
    start_date  DATE         NOT NULL,
    end_date    DATE         NOT NULL,
    CONSTRAINT fk_prescription_doctor
        FOREIGN KEY (doctor_id)
            REFERENCES staff (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_prescription_patient
        FOREIGN KEY (patient_id)
            REFERENCES patient (id)
            ON DELETE CASCADE
);