db.remote.url=jdbc:h2:tcp://192.168.100.50:9092/hospitaldb
db.remote.user=alex_admin
db.remote.password=e367189ab1e5c702f789227e313bfa6e47943682af87f3a4c2e4bba58ba05169
db.local.url=jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE
db.local.user=sa
db.local.password=app